### PR TITLE
Reparent members in clone type

### PR DESCRIPTION
**Pull request by nguerrera**
This caused an issue with the merge with implicit path params into metadata. I ended up needing a param.model === operation.parameters to check that a param is top-level in order to be implicit and it started failing due to cloneType not resetting parent to clone.

### CODE REVIEW

**Comment by nguerrera** [comment]
Ugh this doesn't quite fix it, it's part of the solution. Converting to draft until I get to the bottom of it.

**Comment by nguerrera** [comment]
Seems we're also not reparenting during projection, see also https://github.com/microsoft/cadl/pull/819#issuecomment-1255283189

**Comment by nguerrera** [comment]
Real issue is https://github.com/microsoft/cadl/issues/1069

This is good to fix too but not the problem I was immediately facing.

**Comment by nguerrera** [comment]
Marking ready for review. It's no longer urgent for me, but it does fix a bug.

**Review by timotheeguerin — APPROVED** [review]

**Pull request merged**
