### PR TITLE
Tentative: fix UI test for playground

### PR DESCRIPTION
**Pull request by timotheeguerin**
Playground UI test have been failing so much on windows recently. Trying to
- update packages to see if that would improve.
- change selector to react component

### CODE REVIEW

**Comment by timotheeguerin** [comment]
@nguerrera this didn't seem to resolve the problem, it was horrible yersteday, feels like there was a new failure where it said the page was already closed. Maybe a change to chrome broke playwright on windows.

You can skip test in playwright this way if you want to skip it on windows in the ci https://playwright.dev/docs/test-annotations#conditionally-skip-a-test

**Comment by nguerrera** [comment]
OK, I filed #1223 and staged #1224 to disable the tests on Windows if this persists.

These changes seem good regardless of their impact on the problem. Should we merge this anyway?

**Comment by timotheeguerin** [comment]
Yeah I think those changes are good anyway, will merge

**Pull request merged**
