### PR TITLE
Update enum members to use a map

### LINKED ISSUE #560: Make enum `members` a map like other member containers
I am often annoyed that `members` is a plain array. I think getting the type of an enum member by name will be fairly common? But would also be ok with adding an API to get a member by name.

### PR DESCRIPTION
**Pull request by timotheeguerin**
fix #560

Breaking change release note entry https://github.com/microsoft/cadl/issues/874#issuecomment-1232233934

### CODE REVIEW

**Comment by bterlson** [comment]
Happy to see this! When we did a similar change for unions, we kept the original `options` property as a getter which returns the array of the map's values to avoid breaking changes. Less easy to do here as `members` is probably the name you want to give the good thing, but if we are willing to take this breakage I wonder if we also delete `options` on the Union type?

**Comment by timotheeguerin** [comment]
Guess if we don't want to break anymore we could do the `get` and deprecate it

**Comment by timotheeguerin** [comment]
Yeah sorry, my opinion is breaking doesn't really matter (Specially in the API) until get get to at least beta as long as we document it on the release note.

**Review by bterlson — APPROVED** [review]
+1, let's do this before release this week if possible 😁

**Pull request merged**
