### PR TITLE
Fix binary request & response openapi

### LINKED ISSUE #124: `@body body: bytes` should produce `format: binary` not `format: bytes`
Current having a response like 
```cadl
model Response {
  @contentType: "application/octet-stream";
  @body body: bytes;
}
```

Should produce
```yaml
content: 
  application/octect-stream:
    schema: 
       type: "string"
       format: "binary"

```

fix in: 
- [x] openapi3 https://github.com/microsoft/cadl/pull/125
- [x] cadl-autorest https://github.com/Azure/cadl-azure/pull/1065

### PR DESCRIPTION
**Pull request by timotheeguerin**
resolve openapi3 part of  #124

If request or body is `bytes` and content type is;
- `application/json` => `format: bytes`
- `text/plain` => `format: bytes`
- others => `format: binary`

### CODE REVIEW

**Review by mikekistler — COMMENTED** [review]
I think there is a little too much "magic" (or maybe it is "inconsistent magic") in this design, if I understand it correctly.

My understanding is that we will special case _just one_ return type -- `bytes` -- and interpret it to mean `content-type: application/octet-stream` (by default)
and `type: string, format: binary` (instead of `format: bytes`).

In contrast, return type of `string` is not taken to mean `content-type: text/plain` by default -- the user must specify it explicitly.

I think it would be clearer and simpler to require an explicit content-type whenever it should be different from `application/json`.

Regarding `format: bytes` vs `format: binary`, I recommend a simple rule based on content-type (either explicit or default).  Like
- `bytes` has `format: bytes` iff `content-type` is `application/json`, else `format: binary`, or
- `bytes` has `format: binary` iff `content-type` is `application/octet-stream`, else `format: bytes`

This replaces "special cases" with clear and simple rules.

Thoughts?

**Comment by timotheeguerin** [comment]
@mikekistler, yes it is a fair point. That might be better to do that to start with.
For the option to go I would do #1 otherwise, you can't really specify binary with `image/png` or other content types

**Comment by timotheeguerin** [comment]
@mikekistler actually that might not work. There could be case where the user would want to have application/json be sent as bytes (a raw json file with no schema) if we keep defaulting `application/json` to bytes that would not work.

But we do have to be able to keep representing `type string, format: bytes`, so might need more design

**Comment by mikekistler** [comment]
@timotheeguerin I think you are right that Option 1 is probably best. As for sending json data as bytes (raw), I think that is probably best described as content-type = "application/octet-stream".  I have always taken this to mean "the application will interpret the data", which may not be the precise definition but I think is how it is commonly used.

**Review by markcowl — APPROVED** [review]
I think we need to update the language tuturoail and add in an actual swagger example with both binary and json schema types, but this can be done in later PRs.

**Pull request merged**
