### PR TITLE
Recover better from `op` in interface

### PR DESCRIPTION
**Pull request by nguerrera**
I keep making this mistake and seeing it in @daviwil's video too, I thought it might be worth better deliberate error recovery. I'm not 100% sure if this sort of special casing is worth it or not, but thought I'd offer it up, and see what folks think.

### CODE REVIEW

**Comment by bterlson** [comment]
+1 from me! Special casing for common syntax errors seems super valuable.

**Review by bterlson — APPROVED** [review]

**Review by timotheeguerin — APPROVED** [review]

**Comment by daviwil** [comment]
On the flip side, if this is a common error then maybe the syntax change is confusing and we should keep the op syntax consistent in both contexts? In other words, op should be required even in interfaces

**Comment by nguerrera** [comment]
Yeah, I thought about that too. Was there a strong reason not to have `op` in interfaces. Was it just that it's not necessary with nothing else going in that position than operations?

**Comment by bterlson** [comment]
Also thought about it. There isn't any technical reason to have the op keyword, it's just less verbose and aligns with TS. Another option could be to make i optional, and then prettier would remove i

**Review by markcowl — APPROVED** [review]

**Comment by nguerrera** [comment]
I let this get stale and we didn't have a conclusion so I'm closing this and I filed design issue #262

**Pull request closed without merging**
