### PR TITLE
Feature: `cadl install` command

### PR DESCRIPTION
**Pull request by timotheeguerin**
Doing this as this would let us create a `docker` image with no other dependency on the user side.

Other thing that could be nice is producing a cadl executable which is self contained but then we would need to have npm as a dependency to the compiler.

Adds a new `cadl install` command which just simply shell out to `npm install` and pass through the stdio.

Example: success:
image

Example: Failure to find `npm`:
image

### CODE REVIEW

**Review by bterlson — APPROVED** [review]

**Comment by allenjzhang** [comment]
Is intended user of this feature ourselves or end user? For end-user, it is a chicken/egg situation where you would have to have CADL installed to produce a CADL executables.

**Comment by timotheeguerin** [comment]
> Is intended user of this feature ourselves or end user? For end-user, it is a chicken/egg situation where you would have to have CADL installed to produce a CADL executables.

Yes you still need npm to install `cadl` but this unlocks the ability to use cadl with:
- docker image
- bundled up self-contained executable that can be installed some other way

Without this command we'd still have to have npm installed locally for both those install scenarios

**Comment by allenjzhang** [comment]
Is intended 

> > Is intended user of this feature ourselves or end user? For end-user, it is a chicken/egg situation where you would have to have CADL installed to produce a CADL executables.
> 
> Yes you still need npm to install `cadl` but this unlocks the ability to use cadl with:
> 
> * docker image
> * bundled up self-contained executable that can be installed some other way
> 
> Without this command we'd still have to have npm installed locally for both those install scenarios

I see. Is the assumption be we would add additional param selections for other components such as current cadl vs/cadl code/build package via cadl install?

**Review by allenjzhang — APPROVED** [review]

**Comment by timotheeguerin** [comment]
> I see. Is the assumption be we would add additional param selections for other components such as current cadl vs/cadl code/build package via cadl install?

not exacly sure what you mean. The main idea is to try to start to abstract away the fact that npm is needed on the end user side. We could techinically change to another system later(like yarn). They would only care about running `cadl install` after they  have cadl installed.

**Pull request merged**
