### PR TITLE
add Model type to Cadl.Reflection

### PR DESCRIPTION
**Pull request by iscai-msft**
I want to be able to specify a `Model` in my external decorator docs

### CODE REVIEW

**Comment by nguerrera** [comment]
It's definitely confusing, but the correct way right now to say that a decorator can only applied to a model is `target: object`. We do have an issue  to make `target: Model` possible to make it more readable, but doing so involves some more design and more implementation than what's in this PR.

**Comment by nguerrera** [comment]
https://github.com/microsoft/cadl/issues/1536 is the tracking design issue to make this nicer.

**Review by nguerrera — CHANGES_REQUESTED** [review]
See comments about linked issue and using equivalent `target: object` in the meantime.

**Comment by iscai-msft** [comment]
thanks @nguerrera closing bc it's currently by design to not have Model

**Pull request closed without merging**
