### PR TITLE
Make @route and @autoRoute work together

### LINKED ISSUE #1335: Implementation of `@route` and `@autoRoute` behavior with interfaces and operation reusability.
from design https://github.com/Azure/cadl-azure/issues/1658#issuecomment-1319077819
Updated proposal to allow `@autoRoute` on namespace and not to copy over value from interface down but document this behavior.

| In library                                                       | In service                                  | Resulting route               | With proposal
| ---------------------------------------------------------------- | ------------------------------------------- | ----------------------------- |----
| 1 `@route("one") op action(): void;`                               | `op my is Lib.action;`                      | `/one`                        | `/one`
| 2                                                                 | `@route("my") op my is Lib.action;`         | `/my` or `/my/one`            | `/my`
| 3 `@route("one") interface Ops { action(): void;}`                 | `interface Mys extends Ops {}`              | `/one` or `/my                | `/`
| 4                                                                 | `@route("my") interface Mys extends Ops {}` | `/my/one` or `/my`            | `/my` 
| 5                                                                 | `op my is Lib.Ops.action;`                  | `/one` or `/`                 | `/`  
| 6 `@autoRoute op action(@path @segment("pets") id: string): void;` | `op my is Lib.action;`                      | `/pets/{id}`                  | `/pets/{id}` 
| 7                                                                 | `@route("my") op my is Lib.action;`         | `/my` or `/my/pets/{id}`      | `/my/pets/{id}` 
| 8 `interface Ops { @autoRoute action(...): void;}`                    | `interface Mys extends Ops {}`              | `/{id}` or `/pets/{id}`    | `/pets/{id}` 
| 9                                                                 | `@route("my") interface Mys extends Ops {}` | `/my/{id}` or `/my/pets/{id}` | `/my/pets/{id}` 
| 10 `@autoRoute interface Ops { action(...): void;}`                 | `interface Mys extends Ops {}`              | `/{id}` or `/pets/{id}`       | `/{id}` 
|                                                                  | `@route("my") interface Mys extends Ops {}` | `/my/{id}` or `/my/pets/{id}` | `/my/{id}` 

1. `@route` with `@autoRoute`, should we prepend @autoRoute value with @route? **yes**
    - or don't allow both together
2. Should `@autoRoute` be allowed on namespaces and interface? **yes** but document that is is not portable(maybe library linter?)
    - if allowed maybe emit a warning if not applying @autoRoute on new interface / `op is`
3. Should be allowed to override `@route` on `op is`? **yes**

Key logic:
- routing logic don't respect original parent container but where it is currently defined

### PR DESCRIPTION
**Pull request by tjprescott**
Closes #1335.

**TODO**
- [x] companion PR for cadl-azure - https://github.com/Azure/cadl-azure/pull/2477
- [x] Document using `@route` and `@autoRoute` on an interface is not portable. (Maybe even give warning if using on a templated interface as this will never be used)
- [x] <del>Linter rule for library linter</del>

### CODE REVIEW

**Comment by tjprescott** [comment]
So, I couldn't really put the requested rule in the library-linter because the decorators live in the rest package that the library-linter doesn't have a dependency on. I can put these rules in the rest library linter, but this has the side effect of throwing warnings _everywhere_ including inside specs where using `@route` and `@autoRoute` on interfaces is fine. Could folks weigh in on this?

**Comment by tjprescott** [comment]
Question for @markcowl this changes the behavior if `@route` and `@autoRoute` are used together. Do we consider that a breaking change, or is it a "fixing change"?  How do we want to document that in the release notes?

**Comment by daviwil** [comment]
My feeling is that this would always have been a bug, not a desired feature.  I don't imagine anyone was actually depending on it.  Might be worth running samples in cadl-azure against this change to see what happens.

**Comment by tjprescott** [comment]
@daviwil I did make the companion PR in cadl-azure to verify it has no side effects. In that case, is the added documentation sufficient?

**Pull request merged**
