### PR TITLE
Add double quote to autoClosingPairs

### LINKED ISSUE #1417: [Tooling] Typing " should produce a double-quote pair
In VS Code with the Cadl VS Code extension enabled, typing an open paren will produce an open and closed paren and typing an open curly-brace will produce an open and closed curly-brace.  But typing double-quote `"` produces just a single double-quote.

This is contrast to the behavior of VS Code for TypeScript files, where typing a double-quote produces a double-quote pair, with the cursor after the first double-quote.  

I think VS Code for Cadl should work like VS Code for TypeScript and produce a double-quote pair when a double-quote is typed.

I'd also like this behavior in the Cadl playground.

### PR DESCRIPTION
**Pull request by mikekistler**
This PR adds double quote to the autoClosingPairs for the Cadl language server.

Fixes #1417

### CODE REVIEW

**Comment by nguerrera** [comment]
Re-queued this since the playground failed. That comment dates back to the very first day I played with setting up IDE support for Cadl a long time ago. I don't think I expected it to last this long. 😳 There are other languages have " and """ so I assume there is something we can do. I'll take a quick look to see if they do something smart and if it's easy to steal.

**Comment by nguerrera** [comment]
Hmm, publish to playground is still failing and I was eager to try it. 

@timotheeguerin Any ideas?

<details>

```
Looking for comments in { repo: 'microsoft/cadl', prNumber: '1447' }
Params {
  method: 'GET',
  host: 'api.github.com',
  port: 443,
  path: '/repos/microsoft/cadl/issues/1447/comments',
  headers: { 'User-Agent': 'nodejs' }
}
Found 0 comment(s) from Azure Pipelines.
Found 0 Cadl Try It comment(s)
Params {
  method: 'POST',
  host: 'api.github.com',
  port: 443,
  path: '/repos/microsoft/cadl/issues/1447/comments',
  headers: { 'User-Agent': 'nodejs', 'Content-Type': 'application/json' }
}
Error: Status Code: 403
    at ClientRequest.<anonymous> (file:///mnt/vss/_work/1/s/eng/scripts/create-tryit-comment.js:98:23)
```

</details>

**Comment by timotheeguerin** [comment]
I have seen it fail with those 403 but it doesn't seem to be all the time

**Comment by nguerrera** [comment]
OK requeued 🤞

**Review by timotheeguerin — APPROVED** [review]

**Comment by timotheeguerin** [comment]
/cadl run Cadl Pull Request Try It

**Pull request merged**
