### PR TITLE
Fix: Versioning library not working if multiple instance are used

### LINKED ISSUE #1232: Versioning library does not work when multiple copies of it are loaded
Whilst working on the `cadl-apiview` emitter, I wanted to ensure that the user can specify which version of a spec they want to see the Cadl for. I followed the guidance in the [README](https://github.com/microsoft/cadl/tree/main/packages/versioning#consuming-versioning-library-from-an-emitter), expecting that the projected program would remove references to things which are not supported in the given version. I was confused when the model in question did in fact still appear.

I tested my spec against OpenAPI3 and saw that yes, the generated Swagger omitted the model that was not supported. Debugging into OpenAPI3 (assuming my code was faulty) I found that even when the program is projected to the right version, the projected namespace *still* contains the unsupported model. 

image

In this case, `AmazingNewModel` is not supported by `2022-05-23` and my expectation is that it would be removed from the projected namespace, but it is not. The OpenAPI3 emitter works, so it must be scrubbing the offending model out somehow, but it is neither clear not documented how that happens.

### PR DESCRIPTION
**Pull request by timotheeguerin**
fix #1232

### CODE REVIEW

**Comment by timotheeguerin** [comment]
@tjprescott do you have an easy way to fully verify this is fixing it? I added a test reproducing loading 2 libraries but just wanted to make sure this solve the issue entirely. https://github.com/microsoft/cadl/issues/1232

**Comment by nguerrera** [comment]
Is the other global map, versionCache, OK for some reason?

**Comment by timotheeguerin** [comment]
I think that one is fine as its just a performance caching map.

**Review by nguerrera — APPROVED** [review]

**Comment by tjprescott** [comment]
@timotheeguerin the way I found this in the first place was running Cadl APIView on a spec in the rest API specs repo. I had something in the spec (added) and wasn't omitted when it should have been. @nguerrera was key to actually figuring out the problem, so he would know best.

**Pull request merged**
