### PR TITLE
Show playground diagnostics and internal compiler errors

### LINKED ISSUE #637: Playground doesn't seem to clear previous errors?
See what happens here:

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW50ZXJmYWNlIEZvbzxUPiB7DQogIGJhcigpOiBUO8YNesgNfQ0KDQphbGlhcyBTdHJpbmdGb28gPcU7c8UQPjvEIspVVXNhZ2XGVG9wxFcgacs7LmJhcjsgLy8gZGVsZXRlIGFuZCByZXR5cGXOJA0KfQ%3D%3D)

On my machine I get fairly random errors (e.g. identifier expected on the semicolon, or StringFoo doesn't have member b or ba).

### PR DESCRIPTION
**Pull request by timotheeguerin**
fix #637
### Internal compiler error
[Playground example](https://cadlplayground.z22.web.core.windows.net/prs/639/?c=aW50ZXJmYWNlIEZvbzxUPiB7DQogIGJhcigpOiBUO8YNesgNfQ0KDQphbGlhcyBTdHJpbmdGb28gPcU7c8UQPjvEIspVVXNhZ2XGVG9wxFcgacs7LmJhcjsgLy8gZGVsZXRlIGFuZCByZXR5cGXOJA0KfQ%3D%3D) 
image

### Diagnsostics
[Playground example](https://cadlplayground.z22.web.core.windows.net/prs/639/?c=b3AgdGVzdCgpOiBhYmM7DQrLEWRlZjs%3D)
image

### CODE REVIEW

**Comment by bterlson** [comment]
It should probably scroll when it overflows available space, if it's easy to do (maybe just add an overflow-y: scroll).

**Comment by timotheeguerin** [comment]
right didn't test that, will add it

**Comment by bterlson** [comment]
Hmm, I'm not seeing any scrollability of the error window over here, it still gets cut off.

**Comment by timotheeguerin** [comment]
hhm this works fine for me, was the playground republished already? https://cadlplayground.z22.web.core.windows.net/prs/639/?c=b3AgdGVzdCgpOiBhYmM7Cs8Q3x%2FfH98f3x%2FfH98f3x%2FfH98f3x%2FfH98f3x8%3D

**Comment by bterlson** [comment]
Sorry, confirming this DOES work. I waited for the CI to finish but perhaps I needed to ctrl+F5 the playground or something. Good stuff!

**Review by bterlson — APPROVED** [review]

**Pull request merged**
