### PR TITLE
Add github action to run formatter for you

### PR DESCRIPTION
**Pull request by timotheeguerin**
image

Tested on my fork as you need to have the workflow on the main branch to trigger it https://github.com/timotheeguerin/cadl/pull/2#issuecomment-1289641722

### CODE REVIEW

**Comment by nguerrera** [comment]
Cool!

**Comment by nguerrera** [comment]
Can you do `/cadleng fix bugs` and `/cadleng add more tests` next?

**Comment by timotheeguerin** [comment]
just after `/cadleng design`

**Comment by nguerrera** [comment]
Can you add a note in CONTRIBUTING.md about this?

**Comment by nguerrera** [comment]
Nevermind, you did, sorry.

**Comment by allenjzhang** [comment]
> just after `/cadleng design`

Then `/cadlang make it so` to automatically implement.

**Pull request merged**
