### PR TITLE
Better decorator param validation

### PR DESCRIPTION
**Pull request by timotheeguerin**
Created a new validator helper that provide a few upgrade to the current system:

- Make use of `context.getArgumentAt` to report the right target for an incorrect param
  image
- Provide additional validation for optional params
- Provide validation for the number of params passed
- Make it that you should update the decorator signature types to be what you expect which will be what we'll want for the decorator signature proposal
  ```
  // Before to be type safe and then we used the validator assertion to guide the typing
  export function $foo(context: DecoratorContext, target: Type, arg1: CadlValue) {}

  // Now just define ahead of time which is incorrect without the validation but the validator typing makes sure it is in sync with the definition
  export function $foo(context: DecoratorContext, target: ModelType, arg1: string) {}
  ```

## Usage

```ts
// Step 1: define the decorator definition: This is pretty much what we had before but as individual function call
const headerDecorator = createDecoratorDefinition({
  name: "@header",
  target: "ModelProperty",
  args: [{ kind: "String", optional: true }],
} as const);

// Step 2: update decorator signature to be the types you want
  export function $header(context: DecoratorContext, entity: ModelTypeProperty, headerName?: string)

// Step 3: call validator
if (!headerDecorator.validate(context, entity, [headerName])) {
    return;
  }

```

### CODE REVIEW

**Comment by bterlson** [comment]
Boiling the "let's just define decorators with a compiler API" frog 😂

I like the API, but I wonder if it should vend you the decorator function and take a function callback that is contextually typed? Would be pretty nice to be able to do something like:

```ts
const headerDef = {
  name: "@header",
  target: "ModelProperty",
  args: [{ kind: "String", optional: true }],
};
export const $header = createDecorator(headerDef, (context, entity, headerName) => { // these are contextually typed
  // if called, everything is valid
});
```

**Comment by timotheeguerin** [comment]
haha yeah, that would be much better but I was trying to keep the decorator déclaration still very simple. But I guess doing that doesn’t prevent having a basic function as well. 
only concern now is how does this affect the decorator signature proposal

**Comment by nguerrera** [comment]
Right, I think investing in that contextual typing is sort of investing in an alternate signature proposal, which is based on still more boilerplate than consuming the TS typings + direct idiomatic function definitions in TS. That's maybe OK, but every time decorator signature via some sort of API has come up, it's been shot down. If this contextually typed API can be done quickly and easy and we're willing to replace it with the TS approach, then that's fine. But if it's a lot of work, I'd prefer we spend the time on the TS approach straight away. Or I'd prefer that we have a design consensus to pursue this in favor of the TS approach.

**Comment by nguerrera** [comment]
first observation, go-to-def just works, apparently! Find-all-refs and rename do not, but that's promising.

**Comment by nguerrera** [comment]
Completion also needs work.

**Comment by nguerrera** [comment]
Oh sorry, typing in wrong issue. Will delete and repost.

**Comment by timotheeguerin** [comment]
> Right, I think investing in that contextual typing is sort of investing in an alternate signature proposal, which is based on still more boilerplate than consuming the TS typing + direct idiomatic function definitions in TS. That's maybe OK, but every time decorator signature via some sort of API has come up, it's been shot down. If this contextually typed API can be done quickly and easily, and we're willing to replace it with the TS approach, then that's fine. But if it's a lot of work, I'd prefer we spend the time on the TS approach straight away or have a new design consensus to pursue this in favor of the TS approach before going forward.

@nguerrera  are you specifically talking about the `createDecorator` approach or this design. This is ultimately taking our current validation approach that we have and combining all the validation together so we can make use of the new `DecoratorContext` targets without too much verbosity.

Changing that to the `createDecorator` would be pretty simple from what I have here, all the type inference would already give us that. I think it could also keep some value if one didn't want to write typescript but base JS and still give type info(when we have that ts parsing). At that point the createDecorator could set a property on the decorator function (like namespace) which provide the definition and let the complier do the type checking the same it would for a TS function)

**Comment by nguerrera** [comment]
I was talking about createDecorator.

**Comment by nguerrera** [comment]
> I think it could also keep some value if one didn't want to write typescript but base JS and still give type info(when we have that ts parsing)

Maybe, but this seems much lower priority if we have TS that just works without even a build step. Like I said, If this is easy, then maybe OK, but I'm still a little worried about changing all of the decorator declarations to look different than our currently established end-goal of them just being TS declarations. I suppose it wouldn't be too hard to change them back, but still `createDecorator` feels like pushing in the opposite direction of our previous design consensus.

**Comment by timotheeguerin** [comment]
the other thing that would have made this nice is if JS would allow decorators on function but this wasn't part of the decorator proposal and will be added at a later date
```ts
@decoratorDefinition({
  name: "@header",
  target: "ModelProperty",
  args: [{ kind: "String", optional: true }],
} as const)
export function $header(context: DecoratorContext, entity: ModelTypeProperty, headerName?: string) {

}
```

and then we woudl have been able to just remove the decorator when the TS comes in. Ultimately this is just a syntax sugar for the createDecorator function

**Comment by nguerrera** [comment]
Was the intent here to replace the existing validateDecoratorXxx with this after we reviewed the examples here?

I am happy with this change as-is as a good middle ground that's better than status quo, and we can evolve to either createDecorator or the TS typing or both from here.

**Comment by timotheeguerin** [comment]
yes the goal is to be able to use that instead of all teh individual valudateXYZ methods. If we are happy with this I can do a pass to fix all of that (maybe the same that remove all the warnings in teh libraries)

**Review by nguerrera — APPROVED** [review]

**Pull request merged**
